function audit_table = valenti_table33_parameter_audit(params)
% VALENTI_TABLE33_PARAMETER_AUDIT
% -------------------------------------------------------------------------
% Builds an audit table comparing current adult parameters against Valenti
% Table 3.3. Elastance active amplitudes are computed as Emax - Emin because
% the local model stores peak/passive values.
% -------------------------------------------------------------------------

names = { ...
    'E_A_LA'; 'E_B_LA'; 'V0_LA'; ...
    'E_A_LV'; 'E_B_LV'; 'V0_LV'; ...
    'E_A_RA'; 'E_B_RA'; 'V0_RA'; ...
    'E_A_RV'; 'E_B_RV'; 'V0_RV'; ...
    'R_SYS_AR'; 'C_SYS_AR'; 'L_SYS_AR'; ...
    'R_SYS_C'; 'C_SYS_C'; ...
    'R_SYS_VEN'; 'C_SYS_VEN'; 'L_SYS_VEN'; ...
    'R_PUL_AR'; 'C_PUL_AR'; 'L_PUL_AR'; ...
    'R_PUL_C'; 'C_PUL_C'; 'R_SH'; 'C_SH'; ...
    'R_PUL_VEN'; 'C_PUL_VEN'; 'L_PUL_VEN'; ...
    'R_min'; 'R_max'};

valenti_value = [ ...
    0.38; 0.27; 2.3085; ...
    2.70; 0.069; 3.5385; ...
    0.126; 0.195; 3.5385; ...
    0.43; 0.041264; 8.4067; ...
    0.5911; 1.3315; 2.9643e-4; ...
    2.17e-2; 2.7981e-1; ...
    3.596e-1; 7.5e1; 2.0643e-5; ...
    0.0714; 6.0043; 2.0643e-5; ...
    1.7538e-2; 5.7803; 3.5174e-1; 4.9043e-2; ...
    3.75e-2; 1.1381e1; 2.0643e-5; ...
    6.2872e-3; 9.4168e4];

current_value = [ ...
    params.Emax_la - params.Emin_la; params.Emin_la; params.V0_la; ...
    params.Emax_lv - params.Emin_lv; params.Emin_lv; params.V0_lv; ...
    params.Emax_ra - params.Emin_ra; params.Emin_ra; params.V0_ra; ...
    params.Emax_rv - params.Emin_rv; params.Emin_rv; params.V0_rv; ...
    params.R_sa; params.C_sa; params.L_sa; ...
    params.R_sc; params.C_sc; ...
    params.R_sv; params.C_sv; params.L_sv; ...
    params.R_pa; params.C_pa; params.L_pa; ...
    params.R_pc; params.C_pc; params.R_sh; params.C_sh; ...
    params.R_pv; params.C_pv; params.L_pv; ...
    params.R_mv_min; params.R_mv_max];

unit = { ...
    'mmHg/mL'; 'mmHg/mL'; 'mL'; ...
    'mmHg/mL'; 'mmHg/mL'; 'mL'; ...
    'mmHg/mL'; 'mmHg/mL'; 'mL'; ...
    'mmHg/mL'; 'mmHg/mL'; 'mL'; ...
    'mmHg*s/mL'; 'mL/mmHg'; 'mmHg*s^2/mL'; ...
    'mmHg*s/mL'; 'mL/mmHg'; ...
    'mmHg*s/mL'; 'mL/mmHg'; 'mmHg*s^2/mL'; ...
    'mmHg*s/mL'; 'mL/mmHg'; 'mmHg*s^2/mL'; ...
    'mmHg*s/mL'; 'mL/mmHg'; 'mmHg*s/mL'; 'mL/mmHg'; ...
    'mmHg*s/mL'; 'mL/mmHg'; 'mmHg*s^2/mL'; ...
    'mmHg*s/mL'; 'mmHg*s/mL'};

relative_tolerance = 1.0e-6;    % [fraction] numerical comparison tolerance
absolute_tolerance = 1.0e-10;   % parameter-scale-independent guard

is_match = abs(current_value - valenti_value) <= ...
    max(absolute_tolerance, relative_tolerance * abs(valenti_value));

match_status = repmat({'Match'}, numel(names), 1);
match_status(~is_match) = {'Mismatch'};

audit_table = table(names, valenti_value, current_value, unit, match_status, ...
    'VariableNames', {'parameter_name', 'valenti_value', 'current_code_value', ...
    'unit', 'match_status'});

end
