function targets = valenti_adult_asd_targets(target_set)
% VALENTI_ADULT_ASD_TARGETS
% -------------------------------------------------------------------------
% Returns adult ASD target data reported in Valenti Table 4.4.
%
% INPUT:
%   target_set - 'clinical' or 'model_output'
%
% OUTPUT:
%   targets - table with metric_name, target_value, unit, source, description
% -------------------------------------------------------------------------

if nargin < 1 || isempty(target_set)
    target_set = 'clinical';
end

metric_name = { ...
    'pRA_mean'; ...
    'pRV_max'; ...
    'pRV_min'; ...
    'PAP_max'; ...
    'PAP_min'; ...
    'PAP_mean'; ...
    'PWP_mean'; ...
    'pLV_max'; ...
    'pLV_min'; ...
    'SAP_max'; ...
    'SAP_min'; ...
    'SAP_mean'; ...
    'QP'; ...
    'QS'};

switch lower(target_set)
    case 'clinical'
        target_value = [ ...
            15.0; ...
            45.0; ...
            15.0; ...
            50.0; ...
            20.0; ...
            30.0; ...
            17.0; ...
            98.0; ...
            17.0; ...
            97.0; ...
            70.0; ...
            85.0; ...
            7.86; ...
            3.09];
        source_text = 'Valenti et al. (2023), Table 4.4 clinical value';

    case {'model_output', 'valenti_model_output'}
        target_value = [ ...
            18.36; ...
            49.15; ...
            12.26; ...
            47.0; ...
            19.63; ...
            30.83; ...
            18.76; ...
            98.56; ...
            14.07; ...
            98.07; ...
            69.9; ...
            83.89; ...
            9.44; ...
            3.73];
        source_text = 'Valenti et al. (2023), Table 4.4 model output';

    otherwise
        error('valenti_adult_asd_targets:UnknownTargetSet', ...
            'target_set must be ''clinical'' or ''model_output''.');
end

unit = { ...
    'mmHg'; ...
    'mmHg'; ...
    'mmHg'; ...
    'mmHg'; ...
    'mmHg'; ...
    'mmHg'; ...
    'mmHg'; ...
    'mmHg'; ...
    'mmHg'; ...
    'mmHg'; ...
    'mmHg'; ...
    'mmHg'; ...
    'L/min'; ...
    'L/min'};

source = repmat({source_text}, numel(metric_name), 1);

description = { ...
    'Mean right atrial pressure.'; ...
    'Maximum right ventricular pressure.'; ...
    'Minimum right ventricular pressure.'; ...
    'Maximum pulmonary arterial pressure.'; ...
    'Minimum pulmonary arterial pressure.'; ...
    'Mean pulmonary arterial pressure.'; ...
    'Mean pulmonary wedge pressure, represented by P_pv.'; ...
    'Maximum left ventricular pressure.'; ...
    'Minimum left ventricular pressure.'; ...
    'Maximum systemic arterial pressure.'; ...
    'Minimum systemic arterial pressure.'; ...
    'Mean systemic arterial pressure.'; ...
    'Pulmonary flow.'; ...
    'Systemic flow.'};

targets = table(metric_name, target_value, unit, source, description);

end
