function target_tiers = build_asd_target_tiers(clinical, scenario)
% BUILD_ASD_TARGET_TIERS
% -----------------------------------------------------------------------
% Build ASD-specific target-tier governance for Patient Z pre-closure GSA.
%
% INPUTS:
%   clinical     - Patient Z clinical profile from patient_zoya()       [-]
%   scenario     - scenario string, default 'pre_surgery'               [-]
%
% OUTPUTS:
%   target_tiers - table with target tier and inclusion metadata        [-]
%
% ASSUMPTIONS:
%   - Patient Z pre-closure has pressure-flow targets but missing
%     ventricular volume/function targets.
%   - Q_ASD_Lmin is derived from Qp_Lmin - Qs_Lmin for comparison only,
%     because direct shunt flow is not reported.
%
% REFERENCES:
%   [1] config/patient_zoya.m - clinical source fields.
%   [2] docs/asd_candidate_parameter_set.md - candidate set rationale.
%
% AUTHOR:   Diniya / Codex
% DATE:     2026-05-29
% VERSION:  1.0
% -----------------------------------------------------------------------

if nargin < 2 || isempty(scenario)
    scenario = 'pre_surgery';
end
if nargin < 1 || isempty(clinical)
    clinical = patient_zoya();
end

src = clinical.(scenario);
rows = {};

rows = add_row(rows, 'QpQs', 'QpQs', 'QpQs', ...
    'hard_primary', true, true, read_field(src, 'QpQs'), '-', ...
    'patient_zoya pre-closure cath/clinical record', ...
    'Primary shunt-severity metric.', ...
    'Directly available and central to ASD severity.');
rows = add_row(rows, 'Qp_Lmin', 'Qp_Lmin', 'Qp_Lmin', ...
    'hard_primary', true, true, read_field(src, 'Qp_Lmin'), 'L/min', ...
    'patient_zoya pre-closure cath/clinical record', ...
    'Primary pulmonary-flow target.', ...
    'Use L/min consistently.');
rows = add_row(rows, 'Qs_Lmin', 'Qs_Lmin', 'Qs_Lmin', ...
    'hard_primary', true, true, read_field(src, 'Qs_Lmin'), 'L/min', ...
    'patient_zoya pre-closure cath/clinical record', ...
    'Primary systemic-flow target.', ...
    'Use L/min consistently.');
rows = add_row(rows, 'SAP_mean / MAP', 'SAP_mean', 'SAP_mean_mmHg', ...
    'hard_primary', true, true, read_field(src, 'SAP_mean_mmHg'), 'mmHg', ...
    source_or_default(src, 'SAP_pressure_source', 'investigator-selected systemic pressure'), ...
    'Primary systemic pressure-flow target.', ...
    'Generic SAP_mean is investigator-selected from RFA/cath for this phase.');
rows = add_row(rows, 'PAP_mean', 'PAP_mean', 'PAP_mean_mmHg', ...
    'hard_primary', true, true, read_field(src, 'PAP_mean_mmHg'), 'mmHg', ...
    'patient_zoya pre-closure pulmonary artery pressure', ...
    'Primary pulmonary pressure-load target.', ...
    'Directly available.');
rows = add_row(rows, 'LAP_mean', 'LAP_mean', 'LAP_mean_mmHg', ...
    'hard_primary', true, true, read_field(src, 'LAP_mean_mmHg'), 'mmHg', ...
    'patient_zoya pre-closure left atrial pressure', ...
    'Primary filling-pressure target for ASD operating point.', ...
    'LVEDP is missing; LAP_mean is the available left-sided filling target.');

rows = add_row(rows, 'SAP_max / SBP', 'SAP_max', 'SAP_sys_mmHg', ...
    'soft_secondary', true, true, read_field(src, 'SAP_sys_mmHg'), 'mmHg', ...
    source_or_default(src, 'SAP_pressure_source', 'investigator-selected systemic pressure'), ...
    'Secondary waveform target.', ...
    'Do not let SBP dominate pressure-flow fit.');
rows = add_row(rows, 'SAP_min / DBP', 'SAP_min', 'SAP_dia_mmHg', ...
    'soft_secondary', true, true, read_field(src, 'SAP_dia_mmHg'), 'mmHg', ...
    source_or_default(src, 'SAP_pressure_source', 'investigator-selected systemic pressure'), ...
    'Secondary waveform target.', ...
    'Do not let DBP dominate pressure-flow fit.');
rows = add_row(rows, 'PAP_max / PAP_sys', 'PAP_max', 'PAP_sys_mmHg', ...
    'soft_secondary', true, true, read_field(src, 'PAP_sys_mmHg'), 'mmHg', ...
    'patient_zoya pre-closure pulmonary artery pressure', ...
    'Secondary pulmonary waveform target.', ...
    'Use after mean pulmonary pressure.');
rows = add_row(rows, 'PAP_min / PAP_dia', 'PAP_min', 'PAP_dia_mmHg', ...
    'soft_secondary', true, true, read_field(src, 'PAP_dia_mmHg'), 'mmHg', ...
    'patient_zoya pre-closure pulmonary artery pressure', ...
    'Secondary pulmonary waveform target.', ...
    'Use after mean pulmonary pressure.');
rows = add_row(rows, 'Q_ASD_Lmin', 'Q_ASD_Lmin', 'derived_Qp_minus_Qs', ...
    'soft_secondary_derived_comparison', true, false, derived_qasd(src), 'L/min', ...
    'derived from Qp_Lmin - Qs_Lmin', ...
    'Derived shunt-flow comparison only.', ...
    'Direct ASD shunt flow is missing; do not fit as direct measurement.');

rows = add_row(rows, 'RAP_mean', 'RAP_mean', 'RAP_mean_mmHg', ...
    'prediction_only', false, false, read_field(src, 'RAP_mean_mmHg'), 'mmHg', ...
    'not reported', 'Clinical RAP is missing.', ...
    'Report model prediction only.');
rows = add_row(rows, 'SVR', 'SVR', 'SVR_WU', ...
    'prediction_only', false, false, read_field(src, 'SVR_WU'), 'WU', ...
    'not reported', 'Clinical SVR is missing.', ...
    'May be derived later only if RAP and Qs evidence are defensible.');
rows = add_row(rows, 'PVR', 'PVR', 'PVR_WU', ...
    'prediction_only', false, false, read_field(src, 'PVR_WU'), 'WU', ...
    'not reported', 'Clinical PVR is missing.', ...
    'May be derived later only if pressure-flow assumptions are accepted.');

excluded = {
    'LVEDV', 'LVEDV', 'LVEDV_mL'
    'LVESV', 'LVESV', 'LVESV_mL'
    'RVEDV', 'RVEDV', 'RVEDV_mL'
    'RVESV', 'RVESV', 'RVESV_mL'
    'LVEF',  'LVEF',  'LVEF'
    'RVEF',  'RVEF',  'RVEF'
    };
for idx = 1:size(excluded, 1)
    rows = add_row(rows, excluded{idx, 1}, excluded{idx, 2}, excluded{idx, 3}, ...
        'excluded_missing_volume_function', false, false, read_field(src, excluded{idx, 3}), ...
        unit_for_metric(excluded{idx, 2}), 'not reported', ...
        'Patient Z pre-closure ventricular volume/function target is missing.', ...
        'Exclude from primary GSA and calibration target selection.');
end

target_tiers = cell2table(rows, 'VariableNames', ...
    {'Metric','ModelField','ClinicalField','Tier','IncludeInGSA', ...
    'IncludeInCalibrationLater','ClinicalTarget','Unit','Source', ...
    'Reason','Notes'});
end

function rows = add_row(rows, metric, model_field, clinical_field, tier, ...
    include_gsa, include_calibration, target, unit, source, reason, notes)
% ADD_ROW - append one target governance row.
rows(end + 1, :) = {string(metric), string(model_field), string(clinical_field), ...
    string(tier), logical(include_gsa), logical(include_calibration), target, ...
    string(unit), string(source), string(reason), string(notes)};
end

function value = read_field(src, field_name)
% READ_FIELD - read scalar numeric field or return NaN.
value = NaN;
if isstruct(src) && isfield(src, field_name) && isnumeric(src.(field_name)) && ...
        isscalar(src.(field_name))
    value = src.(field_name);
end
end

function value = derived_qasd(src)
% DERIVED_QASD - derive Q_ASD comparison from Qp-Qs [L/min].
value = NaN;
if isfield(src, 'Qp_Lmin') && isfield(src, 'Qs_Lmin') && ...
        isfinite(src.Qp_Lmin) && isfinite(src.Qs_Lmin)
    value = src.Qp_Lmin - src.Qs_Lmin;
end
end

function source = source_or_default(src, field_name, fallback)
% SOURCE_OR_DEFAULT - read text source field when available.
if isstruct(src) && isfield(src, field_name) && ~isempty(src.(field_name))
    source = char(string(src.(field_name)));
else
    source = fallback;
end
end

function unit = unit_for_metric(metric)
% UNIT_FOR_METRIC - reporting unit for excluded metrics.
if contains(metric, 'EF')
    unit = '-';
else
    unit = 'mL';
end
end
